Web/ArtClubVT.Web/Areas/Administration/Controllers/AdminOrdersController.cs
namespace ArtClubVT.Web.Areas.Administration.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using ArtClubVT.Services.Data.Orders;
    using ArtClubVT.Web.ViewModels;
    using Microsoft.AspNetCore.Mvc;

    public class AdminOrdersController : AdministrationController
    {
        private readonly IOrdersService ordersService;

        public AdminOrdersController(IOrdersService ordersService)
        {
            this.ordersService = ordersService;
        }

        public IActionResult Index()
        {
            var viewModel = this.ordersService.GetAllOrders<OrderViewModel>();
            return this.View(viewModel);
        }

        public IActionResult GetUserOrder(int id)
        {
            var viewModel = this.ordersService.GetOrderAdministration<AdminOrderViewModel>(id);
            return this.View(viewModel);
        }
    }
}

Web/ArtClubVT.Web/Areas/Administration/Views/AdminOrders/GetUserOrder.cshtml
@model AdminOrderViewModel;
@{
    this.ViewData["Title"] = $"Инфо за поръчка Nº {Model.Id}";
}
<h1 class="text-center text-white">@this.ViewData["Title"]</h1>
@if (Model.IsCompleted)
{
    <div class="alert alert-success text-center" role="alert">
        Статус: <strong>ЗАВЪРШЕНА</strong>
    </div>
}
else if (Model.IsConfirmed == false)
{
    <div class="alert alert-danger text-center" role="alert">
        Статус: <strong>Отказана</strong>
    </div>

}
else if (Model.IsConfirmed == null)
{
    <div class="alert alert-warning text-center" role="alert">
        Статус: <strong>Непотвърдена</strong>
    </div>

}
else if (Model.IsConfirmed == true)
{
    <div class="alert alert-success text-center" role="alert">
        Статус: <strong>Потвърдена</strong>
    </div>
}


<div class="text-center text-white buyer-info">
    <img class="img-fluid img-thumbnail custom-shadow col-md-5" src="@Model.ItemImageLink" />
    <ul class="buyer-info-list">
        <p>Продукт - @Model.Item.Name</p>
        <p>Количество - @Model.Quantity бр</p>
        <p>Коментар - @Model.Note</p>
        <p>Име на клиент - @Model.BuyerName</p>
        <p>Телефон на клиент - @Model.BuyerPhone</p>
        <p>Адрес за доставка - @Model.BuyerAddress</p>
        <p>Дата на поръчване - @Model.CreatedOn.ToShortDateString()</p>
    </ul>
</div>

Web/ArtClubVT.Web/Areas/Administration/Views/AdminOrders/Index.cshtml
@using System.Net.NetworkInformation
@model ICollection<OrderViewModel>
@{
    this.ViewData["Title"] = "Направени поръчки:";
}
@if (Model.Any())
{
    <h1 class="text-white">@this.ViewData["Title"]</h1>
    <table class="table table-striped text-center text-white custom-shadow">
        <tr>
            <th>Продукт:</th>
            <th>Количество:</th>
            <th>Създадена от:</th>
            <th>Потвърди:</th>
            <th>Откажи:</th>
            <th>Създадена на:</th>
            <th>Информация:</th>
        </tr>
        @foreach (var order in Model)
        {
            <tr>
                <td>@order.ItemName</td>
                <td>@order.Quantity бр.</td>
                <td><i class="fas fa-envelope"></i> @order.ApplicationUserEmail
                    <a asp-area="Administration" asp-controller="AdminOrders" asp-action="GetUserOrder" asp-route-id="@order.Id" class="btn btn-success">КЛИЕНТ</a></td>

                @if (order.IsConfirmed == null)
                {
                    <td><a asp-area="" asp-controller="Orders" asp-action="ApproveOrder" asp-route-orderId="@order.Id" class="btn btn-success"><i class="fas fa-check-square"></i></a></td>
                    <td><a asp-area="" asp-controller="Orders" asp-action="DeclineOrder" asp-route-orderId="@order.Id" class="btn btn-danger"><i class="fas fa-trash-alt"></i></a></td>
                }
                else if (order.IsConfirmed == false)
                {
                    <td><i class="fas fa-times btn-outline-danger fa-lg"></i></td>
                    <td><i class="fas fa-times btn-outline-danger fa-lg"></i></td>
                }
                else if (order.IsConfirmed == true)
                {
                    <td><i class="fas fa-check btn-outline-success fa-lg"></i></td>
                    <td><i class="fas fa-check btn-outline-success fa-lg"></i></td>
                }

                <td><i class="fas fa-calendar-day"></i> @order.CreatedOn.ToShortDateString()</td>
                <td><a asp-area="" asp-controller="Orders" asp-action="GetOrderInfo" asp-route-id="@order.Id" class="btn btn-info">Информация</a></td>
            </tr>
        }
    </table>
}
else
{
    <h1>Нямате направени поръчки</h1>
}