Web/ArtClubVT.Web/Controllers/CategoriesController.cs
namespace ArtClubVT.Web.Controllers
{
    using System.Threading.Tasks;

    using ArtClubVT.Common;
    using ArtClubVT.Services.Data.Categories;
    using ArtClubVT.Web.ViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class CategoriesController : Controller
    {
        private readonly ICategoryService categoryService;

        public CategoriesController(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }

        public IActionResult GetAll()
        {
            var categories = this.categoryService.GetAllCategories<CategoryViewModel>();
            return this.View(categories);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public IActionResult AddCategory()
        {
            return this.View();
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> AddCategory(string name)
        {
            await this.categoryService.AddCategoryToDbAsync(name);
            return this.RedirectToAction(nameof(this.GetAll));
        }
    }
}

Web/ArtClubVT.Web/Controllers/ItemsController.cs
namespace ArtClubVT.Web.Controllers
{
    using System.Security.Claims;
    using System.Threading.Tasks;

    using ArtClubVT.Common;
    using ArtClubVT.Services.Data.Categories;
    using ArtClubVT.Services.Data.Items;
    using ArtClubVT.Web.ViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class ItemsController : Controller
    {
        private readonly IItemsService itemsService;
        private readonly ICategoryService categoryService;

        public ItemsController(
            IItemsService itemsService,
            ICategoryService categoryService)
        {
            this.itemsService = itemsService;
            this.categoryService = categoryService;
        }

        public IActionResult GetAll()
        {
            var items = this.itemsService.GetAll<ItemViewModel>();
            return this.View(items);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public IActionResult AddItem()
        {
            var viewModel = new CreateItemViewModel();
            viewModel.Categories = this.categoryService.GetAllAsKeyValuePairs();
            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> AddItem(CreateItemViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                model.Categories = this.categoryService.GetAllAsKeyValuePairs();
                return this.View(model);
            }

            await this.itemsService.AddItemToDbAsync(model);

            return this.RedirectToAction(nameof(this.GetAll));
        }

        public IActionResult GetItemsByCategoryName(string categoryName)
        {
            var items = this.itemsService.GetItemsByCategory<ItemViewModel>(categoryName);
            this.ViewBag.CategoryName = categoryName;
            return this.View(items);
        }

        public IActionResult InfoById(int id)
        {
            var item = this.itemsService.GetItemById<ItemViewModel>(id);
            return this.View(item);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public IActionResult EditItem(int id)
        {
            var viewModel = this.itemsService.GetItemById<EditItemViewModel>(id);
            viewModel.Categories = this.categoryService.GetAllAsKeyValuePairs();
            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> EditItem(int id, EditItemViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.itemsService.EditItemAsync(id, input);

            return this.RedirectToAction(nameof(this.InfoById), new { id });
        }

        [Authorize]
        public IActionResult GetUserItems()
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var viewModel = this.itemsService.GetUsersItems(userId);

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> DeleteItem(int id)
        {
            await this.itemsService.DeleteItemAsync(id);
            return this.RedirectToAction(nameof(this.GetAll));
        }

        [Authorize]
        public async Task<IActionResult> AddItemToUserCart(int itemId, int quantity)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            await this.itemsService.AddItemToUserAsync(itemId, userId, quantity);
            return this.RedirectToAction(nameof(this.GetUserItems));
        }

        [Authorize]
        public async Task<IActionResult> RemoveItemFromUserItems(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            await this.itemsService.RemoveItemFromUserItems(id, userId);
            return this.RedirectToAction(nameof(this.GetUserItems));
        }
    }
}

Web/ArtClubVT.Web/Views/Shared/_Layout.cshtml
@using ArtClubVT.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" /> @*This is where to put custom css*@

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />

    <script src="https://kit.fontawesome.com/29d40954af.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar custom-navigation navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-home fa-lg"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="GetAll">Категории</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Items" asp-action="GetAll">Продукти</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="GetUserOrders">Моите поръчки</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="site-content">
        <div class="container">
            <partial name="_CookieConsentPartial" />
            <main role="main" class="pb-3 main-wrapper">
                @this.RenderBody()
            </main>
        </div>
    </div>
   
    
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Поверителност <i class="fas fa-user-secret"></i></a>
            <a class="float-right" href="https://github.com/Boyan-Apostolov/ArtClubVT">Система с отворен код <i class="fab fa-github"></i></a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>